<?php
$nakladove_strediska=array(
1=>array('stredisko_id'=>'0900-00','stredisko_nazov'=>'Hospodársko-technická služba'),
2=>array('stredisko_id'=>'0901-00','stredisko_nazov'=>'Hospodársko-technická služba'),
3=>array('stredisko_id'=>'0901-01','stredisko_nazov'=>'Riaditeľ a sekretariát'),
4=>array('stredisko_id'=>'0901-02','stredisko_nazov'=>'Úsek utajovaných skutočností'),
5=>array('stredisko_id'=>'0901-03','stredisko_nazov'=>'Riadenie kvality'),
6=>array('stredisko_id'=>'0901-04','stredisko_nazov'=>'Dozorný orgán'),
7=>array('stredisko_id'=>'0902-00','stredisko_nazov'=>'Administratívne procesy'),
8=>array('stredisko_id'=>'0902-01','stredisko_nazov'=>'Podporné administratívne procesy'),
9=>array('stredisko_id'=>'0902-02','stredisko_nazov'=>'Podporné prevádzkovo-technické'),
10=>array('stredisko_id'=>'0902-03','stredisko_nazov'=>'Verejné obstarávanie'),
11=>array('stredisko_id'=>'0902-04','stredisko_nazov'=>'Učtovná evid. a správa financií'),
12=>array('stredisko_id'=>'0902-05','stredisko_nazov'=>'Starostliv. a manaž. o pacientov'),
13=>array('stredisko_id'=>'0902-06','stredisko_nazov'=>'Chránené pracovisko - THP'),
14=>array('stredisko_id'=>'0902-07','stredisko_nazov'=>'Odpadové hospodárstvo, ČOV'),
15=>array('stredisko_id'=>'0902-08','stredisko_nazov'=>'BOZP, PO, márnica, metrológ, derat.'),
16=>array('stredisko_id'=>'0902-09','stredisko_nazov'=>'Ostatná prevádzka - holičstvo'),
17=>array('stredisko_id'=>'0904-01','stredisko_nazov'=>'Zabezpečenie personálnej agendy'),
18=>array('stredisko_id'=>'0905-01','stredisko_nazov'=>'Zabezpečenie kontroly'),
19=>array('stredisko_id'=>'0906-01','stredisko_nazov'=>'CO'),
20=>array('stredisko_id'=>'0907-01','stredisko_nazov'=>'Kultúrne zložky, knižnica'),
21=>array('stredisko_id'=>'0908-01','stredisko_nazov'=>'Zabezpečenie IT'),
22=>array('stredisko_id'=>'0909-00','stredisko_nazov'=>'Vrátnica spolu'),
23=>array('stredisko_id'=>'0909-01','stredisko_nazov'=>'Ostatné prevádzka - vrátnica, telef.'),
24=>array('stredisko_id'=>'0909-02','stredisko_nazov'=>'Vrátnica - chránené pracovisko'),
25=>array('stredisko_id'=>'0913-01','stredisko_nazov'=>'Liečebná výživa - stravov. prevádzka'),
26=>array('stredisko_id'=>'0914-01','stredisko_nazov'=>'Práčovňa'),
27=>array('stredisko_id'=>'0915-01','stredisko_nazov'=>'Doprava hospodárska'),
28=>array('stredisko_id'=>'0915-02','stredisko_nazov'=>'Doprava - sanitka'),
29=>array('stredisko_id'=>'0916-00','stredisko_nazov'=>'Údržba vlastná - spolu'),
30=>array('stredisko_id'=>'0916-01','stredisko_nazov'=>'Údržba vlastná - zámočník'),
31=>array('stredisko_id'=>'0916-02','stredisko_nazov'=>'Údržba vlastná - vodoinštalatér'),
32=>array('stredisko_id'=>'0916-03','stredisko_nazov'=>'Údržba vlastná - elektroinštalatér'),
33=>array('stredisko_id'=>'0916-04','stredisko_nazov'=>'Údržba vlastná - stolár'),
34=>array('stredisko_id'=>'0916-05','stredisko_nazov'=>'Údržba vlastná - murár'),
35=>array('stredisko_id'=>'0916-06','stredisko_nazov'=>'Údržba vlastná - maliar'),
36=>array('stredisko_id'=>'0916-07','stredisko_nazov'=>'Chránená dielňa - údržba'),
37=>array('stredisko_id'=>'0918-00','stredisko_nazov'=>'Energetické zdroje spolu'),
38=>array('stredisko_id'=>'0918-01','stredisko_nazov'=>'Kotolne, transformátor, agregát'),
39=>array('stredisko_id'=>'0918-02','stredisko_nazov'=>'Pitná voda'),
40=>array('stredisko_id'=>'0920-01','stredisko_nazov'=>'Ostatná prevádzka - záhrada, dvor'),
41=>array('stredisko_id'=>'0921-01','stredisko_nazov'=>'Ostatná prevádzka - sklad MTZ'),
42=>array('stredisko_id'=>'0923-01','stredisko_nazov'=>'Stravovanie zamestnancov'),
43=>array('stredisko_id'=>'0980-00','stredisko_nazov'=>'Ostatné náklady - spolu'),
44=>array('stredisko_id'=>'0981-00','stredisko_nazov'=>'Bytové hospodárstvo'),
45=>array('stredisko_id'=>'0981-01','stredisko_nazov'=>'Bytovka 66'),
46=>array('stredisko_id'=>'0981-02','stredisko_nazov'=>'Bytovka 67'),
47=>array('stredisko_id'=>'0981-03','stredisko_nazov'=>'Bytovka 68'),
48=>array('stredisko_id'=>'0981-04','stredisko_nazov'=>'Bytovka 69'),
49=>array('stredisko_id'=>'0981-05','stredisko_nazov'=>'Bytovka 70'),
50=>array('stredisko_id'=>'0981-06','stredisko_nazov'=>'Bytovka 71'),
51=>array('stredisko_id'=>'0981-07','stredisko_nazov'=>'Špano, Levická 114'),
52=>array('stredisko_id'=>'0981-08','stredisko_nazov'=>'Bytovka, Levická 64'),
53=>array('stredisko_id'=>'0982-00','stredisko_nazov'=>'Prenájom zdrav. zariadeniam'),
54=>array('stredisko_id'=>'0982-01','stredisko_nazov'=>'Prenájom zdrav. zariadeniam'),
55=>array('stredisko_id'=>'0983-00','stredisko_nazov'=>'Prenájom org. mimo rez. zdrav.'),
56=>array('stredisko_id'=>'0983-01','stredisko_nazov'=>'Terénna terapia'),
57=>array('stredisko_id'=>'0983-02','stredisko_nazov'=>'Nebytové priestory'),
58=>array('stredisko_id'=>'0986-00','stredisko_nazov'=>'Vedľajšia hospod. činnosť'),
59=>array('stredisko_id'=>'0986-01','stredisko_nazov'=>'VHČ - chránená dielňa'),
60=>array('stredisko_id'=>'0986-02','stredisko_nazov'=>'VHČ - agroturistika'),
61=>array('stredisko_id'=>'0986-04','stredisko_nazov'=>'VHČ - pranie prádla'),
62=>array('stredisko_id'=>'0986-05','stredisko_nazov'=>'VHČ-CHP - údržba a oprava jazde.'),
63=>array('stredisko_id'=>'0999-00','stredisko_nazov'=>'Zariad. podpor. bývania - spolu'),
64=>array('stredisko_id'=>'0999-01','stredisko_nazov'=>'Chránené bývanie'),
65=>array('stredisko_id'=>'0999-02','stredisko_nazov'=>'Zariad. podpor. bývania NSK'),
66=>array('stredisko_id'=>'0999-03','stredisko_nazov'=>'Zariad. podpor. bývania BSK'),
67=>array('stredisko_id'=>'0999-04','stredisko_nazov'=>'Ustajnenie zvierat'),
68=>array('stredisko_id'=>'1000-00','stredisko_nazov'=>'Lôžkové oddelenie spolu'),
69=>array('stredisko_id'=>'1005-00','stredisko_nazov'=>'Psychiatrické oddelenie spolu'),
70=>array('stredisko_id'=>'1005-01','stredisko_nazov'=>'Akútne ženské oddelenie'),
71=>array('stredisko_id'=>'1005-02','stredisko_nazov'=>'Oddelenie dlhodobej liečby - ženy'),
72=>array('stredisko_id'=>'1005-03','stredisko_nazov'=>'Akútne mužské oddelenie'),
73=>array('stredisko_id'=>'1005-04','stredisko_nazov'=>'Oddelenie dlhodobej liečby - muži'),
74=>array('stredisko_id'=>'1073-01','stredisko_nazov'=>'Liečba toxikomanií'),
75=>array('stredisko_id'=>'1074-01','stredisko_nazov'=>'Gerontopsychiatrické oddelenie'),
76=>array('stredisko_id'=>'2000-00','stredisko_nazov'=>'Ambulancie spolu'),
77=>array('stredisko_id'=>'2005-01','stredisko_nazov'=>'Psychiatrická ambulancia'),
78=>array('stredisko_id'=>'2027-01','stredisko_nazov'=>'Rehabilitačná ambulancia'),
79=>array('stredisko_id'=>'3000-00','stredisko_nazov'=>'Pracoviská'),
80=>array('stredisko_id'=>'3978-00','stredisko_nazov'=>'Oddeleniepre ošetr. a liečeb. star.'),
81=>array('stredisko_id'=>'3978-01','stredisko_nazov'=>'Závodná sestra, konziliar. čist.'),
82=>array('stredisko_id'=>'3978-02','stredisko_nazov'=>'Sociálny úsek - sociálne sestry'),
83=>array('stredisko_id'=>'3978-03','stredisko_nazov'=>'Prerozdelenie liekov'),
84=>array('stredisko_id'=>'3978-04','stredisko_nazov'=>'Biologická terapia'),
85=>array('stredisko_id'=>'5000-00','stredisko_nazov'=>'SVaLZ spolu'),
86=>array('stredisko_id'=>'5024-01','stredisko_nazov'=>'OKB'),
87=>array('stredisko_id'=>'5027-01','stredisko_nazov'=>'Centrálna rehabilitácia')
);
?>